### ISSUE TITLE
ci: migrate from TravisCI to CircleCI

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11592]
### What is the expected behavior?
That we migrate over to CircleCI.

### What is the current behavior?
We run most all of our CI on TravisCI. In general, it has been working fine other than some outages. We recently setup Firefox and Chrome to run in Headless mode and removed our use of Saucelabs.

### What is the use-case or motivation for changing an existing behavior?
Our paid plan with TravisCI will end on January 31st, 2019. This will lead to longer queue times for builds. The Angular team has moved over to CircleCI for angular/angular, angular/material, and some of the other repos. We need to do the same in order to benefit from faster builds, paid support, etc.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material: 1.1.12
- OS: macOS
- Browsers: Chrome, Firefox
 
## TODO
- [x] Configure CircleCI to run the tests against AngularJS 1.5, 1.6, 1.7, and snapshot for `master` and PRs
- [x] Enable CircleCI for `angular/material`
- [x] Define `ANGULARJS_MATERIAL_BOWER_TOKEN` and `ANGULARJS_MATERIAL_DOCS_SITE_TOKEN ` Github Push Tokens as CircleCI environment variables
- [x] Disable TravisCI completely
- [x] Enable CircleCI to deploy to bower-material and update the `HEAD` docs site on commits to `master`

**Comment by Splaktar** [comment]
CircleCI is configured and appears to be working correctly for PRs and commits to `master`.
