### ISSUE TITLE
md-virtual-repeat to-do list

### ISSUE THREAD

**Issue by kseamon** [angular/material#3368]
- [x] update md-virtual-repeat-container support **attribute** directive usages
- [x] make md-item-size optional (read item size from dom)
- [x] scrollTo method on container controller
- [x] ability to resize (shrink) container when the number of items is too small to fill it
- [x] better detection of whether the container is hidden (just checks for ng-hide right now) (might be able to sidestep by using getComputedStyle to read the height) and other height changes
- [ ] Detect additional elements in the container and adjust available height accordingly
- [ ] unit tests for public controller methods
- [x] horizontal demo
- [ ] note limitations in documentation (no one-time bind, needs consistent item size, might have screen reader problems in some use-cases)
- [ ] Unit tests for md-on-demand

**Comment by gkalpak** [comment]
[ ] detect the actual size of the scrollbar

**Comment by epelc** [comment]
Would this be similar to ionic's collection repeat?

http://ionicframework.com/docs/api/directive/collectionRepeat/

**Comment by ajoslin** [comment]
How's the mobile support for this component?

**Comment by ThomasBurleson** [comment]
@kseamon - note 

*  Ionic's use of `<ion-scroll direction="x" class="available-scroller">` in their [collection-repeat](http://ionicframework.com/docs/api/directive/collectionRepeat/).
*  No need to explicitly specify a repeat *container*

> Should we be consistent with well-known APIs and use `md-collection-repeat` instead of `md-virtual-repeat` ?

**Comment by kseamon** [comment]
@epeic Looks like it is pretty similar to Ionic's repeater.

**Comment by kseamon** [comment]
@ajoslin We've tested it in Android Chrome and iOS 8.

**Comment by kseamon** [comment]
@ThomasBurleson Do they have the option to specify one? I agree that we should make it optional, but it's a feature that we absolutely will need for a lot of components.

**Comment by epelc** [comment]
@ThomasBurleson I'd recommend not including `collection-repeat` in the name unless you are going to move ionic's collection repeat to another repo and use that in both projects.

Something different would help with the googleablilty for any problems/tutorials about it. It would also cause less confusion for developers.

**Comment by jaruesink** [comment]
I was able to get virtual-scroll to work great when the list items were one per row. But as my screen gets larger I shorten their width so I include multiple items per row and this throws everything off. It makes sense why it doesn't work right now, but it would be nice to be able to dynamically set the number of items per row or something like that.

**Comment by bluebirdtech** [comment]
Any idea how I access the container controller to call the scrollTo() function?  I need to scroll to show a particular item.

**Comment by antoinebrault** [comment]
Any plans on supporting md-virtual-repeat in a table ? 
md-virtual-repeat-container on <tbody> and  md-virtual-repeat on <tr>

**Comment by dohomi** [comment]
I'm facing same problem as @jaruesink describes. Would be great for setting number of items with multi-column-cells.

**Comment by wembernard** [comment]
+1 for the multi-column-cells feature :thumbsup:

**Comment by bluebirdtech** [comment]
Would be great to support variable height rows.  Use-case: A list with headers.  Right now headers need to be chunky.  Keen to hear about any workarounds anyone is using in the meantime.

**Comment by wembernard** [comment]
@bluebirdtech I'm using ngInfiniteScroll (https://github.com/sroze/ngInfiniteScroll) which is a nice workaround.

**Comment by bluebirdtech** [comment]
Thanks @wembernard.  For this case the number of items is known and having the scrollbar cover the full range of values is preferable.  We're sending back header titles and indices on the initial request (and pulling down content rows in batches on demand), so it is possible to calculate an exact height of the scrollable region initially.

**Comment by RolandHeath** [comment]
@bluebirdtech not sure if it applies to your situation, but I'm simulating a table header row at the moment by leaving the top row of the md-list out of the virtual repeat. When it scrolls, that acts like a sticky header, so it might not be desirable for your use case.

**Comment by bluebirdtech** [comment]
@RolandHeath Thanks, we're also doing that.  The sticky header row is separate so that it's not affected by virtualization.  It's behaves as a transparent overlay (absolute positioned) that gets pushed out of the way when the next header moves up, like with iOS sectioned list headers.  It's working very well, apart from the chunkiness of header rows caused by needing to keep all rows a consistent height: 
![sticky-header-example-3](https://cloud.githubusercontent.com/assets/3141867/9627991/dc473104-515f-11e5-8b40-519ac4fa53f7.png)

**Comment by RonB** [comment]
@ThomasBurleson or @kseamon 

Maybe not the best place to ask, but I'm exited about this functionality, just having diffculty to understand the api. I'm confused on how this VirtualRepeatModel should work. I have defined a class using a factory like so:

    angular.module('app' )
            .factory(
                    'Store',
                    function ($http) {

                        function Store(options) {
                            // params for the api-call are passed thru the options parameter
                            this.params = options || {};
                            // limit page size
                            this.params.limit = this.params.limit || 100;
                            // start at offset
                            this.offset = 0;
                            // data array ???
                            this.data = [];
                            // keymap
                            this.keys = {};
                            // init first page
                            this.fetch_(0);
                        }

                        // Required.
                        Store.prototype.getItemAtIndex = function (index) {
                            if (this.data[index]) {
                                return this.data.index;
                            } else {
                                this.fetch_(index);
                            }
                        };
                        
                        // Required.
                        Store.prototype.getLength = function () {
                            return this.data.length;
                        };
                        // fetch a page with data
                        Store.prototype.fetch_ = function (offset) {
                            this.params.offset = offset || 0;
                            var url = '/api/' + this.params.schema + '/search';
                            $http({
                                url: url,
                                method: 'get',
                                params: this.params
                            }).then(angular.bind(this, function (response) {
                                  this.offset += response.data.rows.length;
                                  angular.forEach(response.data.rows, function (row) {
                                      this.data.push(row);
                                      this.keys[row.docunid] = this.data[this.data.length-1];
                                  }, this);
                            }));
                        };
                        return Store;
                    });


In my controller:

    $scope.employees = new Store({schema: 'employee'});

I want to iterate over the data array, but in your example you seem to have the data stored in the loadedPages object, which is not used as such in the markup. I cannot use 

    <md-virtual-repeat-container >
                <div md-virtual-repeat="employee in employees" md-on-demand>{{ employee.name }}</div>
    </md-virtual-repeat-container>

because the employees are stored in the "data" array of the store. What am I missing here?

**Comment by colinskow** [comment]
Is there a way to access the toScroll function publicly from the parent controller?

**Comment by begemott** [comment]
+1 to  Detect additional elements in the container and adjust available height accordingly 
And it would be great if the virtual repeat supports rows of different height just like ionic's collection-repeat.

**Comment by evanjmg** [comment]
Does virtual repeat support same height inline-block-items or flex items ? I want three items of the same height across.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (424/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:39497 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZm-001Z84-Ft
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:19 +0200
Date: Thu, 28 Apr 2016 13:27:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875265;
	bh=ews4xaKPi+pw1NMWtJJfYA72AGLpYXc+MvB7o3z88/0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=sFTqiW//5G1jp4D50NYK/m8Qbvh9lJynwkbgwdxSjEVHN3ym8MHdfEQOcBUfs3mCj
	 B0OVNKUjSFXAkebZV2bDpKrRw9J0n4FJYQDMCtTuB0oXm06wBjNAAMFxXRQEdnOH3/
	 0jVXHrep40O3u3ptCHqMPzWlf9vkR+7Ph6Uhl/yA=

**Comment by ananyaojha** [comment]
Can someone help me out how to implement virtual repeater with infinite scrolling?

Requirement: 
We have to show list of posts. for getting post list, we are sending ajax call and getting 16 posts at a time and again on scroll next 16 posts n so on. I need to implement virtual repeater here where on load first 16 posts should load and then on scroll next 16 n so on.

THe variable im using in virtual repeater must be a scope vara=iable so that i can dispaly posts.

CODE:

app.controller('stateController', ['$scope', '$rootScope', '$state', '$stateParams', '$http', '$q', 'CategoryService', 'UserService', 'LocalDataStore', 'locationTrackerFactory', '$cookieStore', function ($scope, $rootScope, $state, $stateParams, $http, $q, CategoryService, UserService, LocalDataStore, locationTrackerFactory, $cookieStore) {
    
    var session = UserService.getSession(),
        config = {
            docFilters: []
        };

    // In this example, we set up our model using a plain object.
    // Using a class works too. All that matters is that we implement
    // getItemAtIndex and getLength.
    this.infiniteItems = {
        numLoaded_: 0,
        toLoad_: 0,
        items: [],

        // Required.
        getItemAtIndex: function(index) {
            if (index > this.numLoaded_) {
              this.fetchMoreItems_(index);
              return null;
            }

            return this.items[index];
        },

        // Required.
        // For infinite scroll behavior, we always return a slightly higher
        // number than the previously loaded items.
        getLength: function() {
            return this.numLoaded_ + 5;
        },

        fetchMoreItems_: function(index) {
            // For demo purposes, we simulate loading more items with a timed
            // promise. In real code, this function would likely contain an
            // $http request.

            if (this.toLoad_ < index) {
                this.toLoad_ += 5;

                var params = [];
        
                params.push('brandId=' + encodeURIComponent(brandId));
                params.push('sessionToken=' + session.token);
                params.push('userId=' + session.userId);
                params.push('categoryDocId=' + encodeURIComponent('Cat::Events:PreWeddingCelebrations'));
                params.push('subCategoryIds=' + config.docFilters.join(','));
                params.push('featuredFlag=0');        
                params.push('userFlag=1');
                params.push('userStatsFlag=1');
                params.push('channelFlag=1');
                params.push('childPostsFlag=0');
                params.push('ignoreShop=0');
                params.push('offset=' + this.items.length);
                params.push('limit=16');
                params.push('orderBy=' + 'date');

                $http({
                    method: 'POST',
                    url: apiUrl + 'posts/getPostsByCategory',
                    data: params.join('&')
                })
                .success(function (data) {
                // .then(angular.bind(this, function (data) {
                    if (data && data._responseStatus) {
                        var items = data.postJson;
                        for (var i = 0; i < items.length; i++) {
                            this.items.push(items[i].data);
                        }
                        
                        this.numLoaded_ = this.toLoad_;
                    }
                });
            }
            
        }
    };
    console.log(this.infiniteItems)
}]);



<md-content layout="column">
    <md-virtual-repeat-container id="vertical-container">
        <div md-virtual-repeat="item in infiniteItems" md-on-demand class="col-md-3 col-sm-4 post_card_wrap desktop-view repeated-item" flex>
            {{item.postTitle}}
        </div>
    </md-virtual-repeat-container>
</md-content>


I have already setup controller name in app.js so no need to set up here again. But, I cant figure out how to set up the variable in scope.
