### ISSUE TITLE
Improve UX for Material API documentation

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#916]
The current API section of the Angular Material documentation needs improvements. We should consider:

 - the API presentation in [UI Router](http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$templateFactory)
 - the [API documentation](https://docs.angularjs.org/api/ng/directive/ngClick) for AngularJS 1.x
 - the planned API docs for Angular 2.x. (talk with @petebacondarwin )

 > We may need to enhance our jsDocs, update the gulp and CSS, etc.

<h2>Checklist:</h2>

- [x] Docs menu items in more common Guides/Tutorials/Resource structure (IA), restyled to use [expand/collapse list controls](http://www.google.com/design/spec/components/list-controls.html#list-controls-types-of-list-controls)  https://github.com/angular/material/pull/1116
- [x] Add real-world examples https://github.com/angular/material/issues/1102
- [x] Restyle API services & directives into more readable format https://github.com/angular/material/issues/984
- [ ] Simplify API toolbar buttons, add Search https://github.com/angular/material/issues/917
- [ ] Add version picker https://github.com/angular/material/issues/918

**Comment by epelc** [comment]
Please do not base it too heavily on `ui-router`'s docs. I find them extremely lacking and I always have to jump between them and their wiki pages.

**Comment by marcysutton** [comment]
@epelc the only part of UI-Router's docs that was considered was how methods were displayed. But I will keep that in mind.
